// quotes.js  —  random quote for The Sunken Fate
window.QUOTES = [
  "pay attention during school",
  "yall playing games while im making the website ur using",
  "shout out to whoever spent 2 hours on snake",
  "The Sunken Fate >>> 3kh0",
  "ive currently lost $4 on this website",
  "join the discord NOW",
  "have any of you played on the og padlet?",
  "linux is so much better than windows",
  "🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸🇵🇸",
  "chromebooks suck",
  "technoblade never dies",
  "The Sunken Fate has shut down.",
  "theres at least 2, maybe 3 games on this website",
  "yall failing ur classes while im a straight A student in all honors",
  "just maybe stole a bunch ideas from 3kh0",
  "why is 1v1lol the most popular game",
  "https://discord.gg/7jyufnwJNf",
  "buy smth from the patreon so i dont have to be in debt anymore",
  "https://skysthelimit.dev",
  "https://github.com/selenite-cc",
  "use the transfer tool to keep ur data from other websites",
  "best way to bypass the filter is on my patreon! (i wrote this as a joke but its real now)",
  "best proxy ever only on my patreon (i wrote this as a joke but its real now)",
  "🥺👉👈",
  "what website is this?",
  "we love about:blank",
  "make sure to back up ur saves incase we ever get blocked",
  "join the discord to be cool",
  "rip bigfoot games shack 🕊",
  "check steam",
  "selentine",
  "geometry dash two point two",
  "does anyone call twitter X unironically",
  "why is there like a hundred solo.to pages that have The Sunken Fate, literally just search \"site:solo.to The Sunken Fate\"",
  "hey",
  "happy new years everyone",
  "merry christmas everyone",
  "happy easter day everyone",
  "happy halloween everyone",
  "happy thanksgiving everyone",
  "happy valentines day everyone",
  "happy birthday to me",
  "happy birthday to you",
  "happy birthday to everyone",
  "happy birthday to the website",
  "dont look behind you",
  "sky",
  "penguinify",
  "a456ph",
  "The Sunken Fate",
  "yocorvettekid loves gay men",
  "3kh0",
  "bigfoot games shack",
  "The Sunken Fate is the best",
  "The Sunken Fate is the best website",
  "The Sunken Fate is the best website ever",
  "The Sunken Fate is the best website ever made",
  "The Sunken Fate is the best website ever made in the history of the world",
  "The Sunken Fate is the best website ever made in the history of the world and the universe",
  "The Sunken Fate is the best website ever made in the history of the world and the universe and the galaxy",
  "The Sunken Fate is the best website ever made in the history of the world and the universe and the galaxy and the solar system",
  "The Sunken Fate is the best website ever made in the history of the world and the universe and the galaxy and the solar system and the milky way",
  "Your network admin has logged this visit. You will be reported to the authorities.",
  "share with your friends",
  "i love piracy",
  "i love piracy and you should too",
  "ai is gonna take over the world",
  "serap",
  "slenetine"
];

// inject a random quote into #quote-box on homepage
document.addEventListener('DOMContentLoaded', () => {
  const box = document.getElementById('quote-box');
  if (!box) return;
  // replace any case of "selenite" with "The Sunken Fate" before display
  let q = QUOTES[Math.floor(Math.random() * QUOTES.length)];
  q = q.replace(/selenite/gi, "The Sunken Fate");
  box.textContent = q;
});
